name: QA Br to Fullcopy Deploy
on: 
  push:
    branches:
      - 'QA'

jobs:
  SFDX-CLI-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - run: echo "ðŸ§ GitHub Action running on ${{ runner.os }}"
      - run: echo "ðŸ”Ž Retrieving Dev Branch from ${{ github.repository }}."
      - uses: actions/checkout@v4
        with: 
          ref: 'QA'
      - name: 'Read PR Body'
        env:
          PR_BODY: ${{ github.event.head_commit.message }}
        run: |
              echo "Value of pr body is $PR_BODY"
              echo $PR_BODY > .github/workflows/pr_body.txt
              echo "cat .github/workflows/pr_body.txt"
              node .github/workflows/parsePR.js
              TESTS=$(cat .github/workflows/testsToRun.txt)
              echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV
              echo "APEX_TESTS=$TESTS"
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --help
          pip install xq
          pip install yq
      - name: Install sfdxGit delta
        run: |
          echo y | sf plugins install sfdx-git-delta
          sf sgd:source:delta --to "HEAD" --from "HEAD~1"  --output "." --ignore .github/workflows/ignore.txt
          cat package/package.xml
      
      - name: Authenticate to Salesforce
        run: |
          echo ${{ secrets.SF_AUTH_URL }} > sfdx-auth-url.txt
          sfdx auth:sfdxurl:store --sfdx-url-file sfdx-auth-url.txt
     
      - name: Deploy Delta components to Salesforce RunSpecifiedTests
        if: ${{ env.APEX_TESTS != 'all' }}
        run: |
          sf project deploy validate --manifest package/package.xml --test-level RunSpecifiedTests --tests ${{ env.APEX_TESTS }} --target-org qa 

      - name: Deploy Delta components to Salesforce RunLocalTests
        if: ${{ env.APEX_TESTS == 'all' }}
        run: |
            sf project deploy validate --manifest package/package.xml --test-level RunLocalTests --target-org qa 